/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author MC
 */
public class SerieC extends javax.swing.JInternalFrame {
    String memoria;
    /**
     * Creates new form SerieC
     */
    public SerieC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        texto = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Capacitores En Serie ");

        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Titulo.setText("Ingrese los capacitores separados por una coma y con la misma dimensional");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo)
                    .addComponent(jButton1)
                    .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButton1)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String resultado;
        memoria=texto.getText();
        resultado=calculadora(memoria);
        texto.setText(resultado);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables

    public static  String calculadora(String memoria) {
         String numeros[] = memoria.split("\\,");
         
         float calculo = 0, a, f, r = 0;

    for(String elemento : numeros){
        try {
             if (numeros.length == 2)
                {
                calculo = (Float.parseFloat(numeros[0].trim())*Float.parseFloat(numeros[1].trim()))/(Float.parseFloat(numeros[0].trim())+Float.parseFloat(numeros[1].trim()));
               
                } else {
                    for (int i = 1; i <numeros.length; i++) {
                    f=Float.parseFloat(numeros[i-1].trim());
                    a = 1/f;
                    r = a+r;
                } calculo=1/r;
                }
                                {
                   
            }
        } catch (NumberFormatException e) {
            System.out.println("No se puede realizar la operacion debibo a que: "+elemento+" no es un numero valido.");
            e.printStackTrace();
            return "No valido";
        }
    }

    return String.valueOf(calculo); //To change body of generated methods, choose Tools | Templates.
    }
}
